### ISSUE TITLE
Add fakedns

### ISSUE THREAD

**Issue by misagh72** [sudospaes/x-ui#18]
Hello 
Can you add fakedns 
https://github.com/alireza0/x-ui/commit/5b9c3f83eaec6555518833125e327bfeee7f396e

**Comment by sudospaes** [comment]
Sure, but for next update

**Comment by sudospaes** [comment]
Hello again :) this is added to [v0.4.5.1](https://github.com/sudospaes/x-ui/releases/tag/v0.4.5.1)
