### ISSUE TITLE
encoding xray Error

### ISSUE THREAD

**Issue by ehsani967** [sudospaes/x-ui#28]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Its my problem 
what i have to do??

### Version of x-ui

<details>

Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 linux/amd64)

A unified platform for anti-censorship.

2023/05/21 20:45:18 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: main: failed to load config files: [bin/config.json] > encoding/hex: invalid byte: U+0074 't'
</details>

![Capture](https://github.com/sudospaes/x-ui/assets/125989227/bc96a17a-c125-4e1e-8a78-f3b5ea391bce)

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by sudospaes** [comment]
Hello Pls send your x-ui log

**Comment by ehsani967** [comment]
Hello It was a issue in the uuid encoding becuase it was 9 parameters 
Thanks for ur Best xray fork
