### ISSUE TITLE
list of users

### ISSUE THREAD

**Issue by saman-magnus** [sudospaes/x-ui#3]
hello , the new version have this bugs /
They are not visible in the list of users.
 the refresh key is constantly rotating
The ability to add users has been completely lost
thanks
![showing](https://github.com/sudospaes/x-ui/assets/41460065/9bec8b95-ec7a-430e-8479-fd2117f39278)

**Comment by saman-magnus** [comment]
i didn't find any issue in log file , but i shared here
[x-ui.log](https://github.com/sudospaes/x-ui/files/11681678/x-ui.log)

`Jun 08 05:23:12 saman-sevr systemd[1]: Stopped x-ui.service - x-ui Service.
Jun 08 05:23:12 saman-sevr systemd[1]: x-ui.service: Consumed 7.347s CPU time.
Jun 08 05:23:12 saman-sevr systemd[1]: Started x-ui.service - x-ui Service.
Jun 08 05:23:12 saman-sevr x-ui[2842]: 2023/06/08 05:23:12 x-ui 0.4.2.0
Jun 08 05:23:12 saman-sevr x-ui[2842]: 2023/06/08 05:23:12 INFO - web server run https on [::]:8443
Jun 08 05:24:32 saman-sevr x-ui[2842]: 2023/06/08 05:24:32 WARNING - stop server err: multierr: close tcp [::]:8443: use of closed network connection |
Jun 08 05:24:32 saman-sevr x-ui[2842]: 2023/06/08 05:24:32 INFO - web server run https on [::]:8443
Jun 08 05:34:01 saman-sevr x-ui[2842]: 2023/06/08 05:34:01 http: TLS handshake error from 192.168.1.1:44704: remote error: tls: bad certificate
Jun 08 05:34:07 saman-sevr x-ui[2842]: 2023/06/08 05:34:07 http: TLS handshake error from 192.168.1.1:44717: remote error: tls: bad certificate
Jun 08 05:34:15 saman-sevr x-ui[2842]: 2023/06/08 05:34:15 http: TLS handshake error from 192.168.1.1:44722: read tcp 192.168.1.70:8443->192.168.1.1:44722: use of closed network connection
Jun 08 05:34:15 saman-sevr x-ui[2842]: 2023/06/08 05:34:15 http: TLS handshake error from 192.168.1.1:44723: read tcp 192.168.1.70:8443->192.168.1.1:44723: use of closed network connection
Jun 08 05:34:22 saman-sevr x-ui[2842]: 2023/06/08 05:34:22 http: TLS handshake error from 192.168.1.1:44751: remote error: tls: bad certificate
Jun 08 05:34:33 saman-sevr x-ui[2842]: 2023/06/08 05:34:33 INFO - Saman login success ,Ip Address: 192.168.1.1
Jun 08 05:34:33 saman-sevr x-ui[2842]: 2023/06/08 05:34:33 INFO - user 1 login success
Jun 08 05:42:14 saman-sevr x-ui[2842]: 2023/06/08 05:42:14 http: TLS handshake error from 45.55.0.32:49640: tls: client offered only unsupported versions: []
Jun 08 06:22:39 saman-sevr x-ui[2842]: 2023/06/08 06:22:39 http: TLS handshake error from 192.168.1.1:45505: read tcp 192.168.1.70:8443->192.168.1.1:45505: use of closed network connection
Jun 08 06:22:39 saman-sevr x-ui[2842]: 2023/06/08 06:22:39 http: TLS handshake error from 192.168.1.1:45506: read tcp 192.168.1.70:8443->192.168.1.1:45506: use of closed network connection
Jun 08 06:22:46 saman-sevr x-ui[2842]: 2023/06/08 06:22:46 INFO - Saman login success ,Ip Address: 192.168.1.1
Jun 08 06:22:46 saman-sevr x-ui[2842]: 2023/06/08 06:22:46 INFO - user 1 login success
Jun 08 06:24:03 saman-sevr x-ui[2842]: 2023/06/08 06:24:03 WARNING - Create Fail:  Port already exists: 10114`

**Comment by saman-magnus** [comment]
I completely deleted the program. And I installed it again. I came to the conclusion that by introducing the old database, the program faces problems. and crashes. 
Thanks for your response

**Comment by sudospaes** [comment]
> I completely deleted the program. And I installed it again. I came to the conclusion that by introducing the old database, the program faces problems. and crashes. Thanks for your response

What database did you give it?

**I will delete your log from here so that your IP is not visible**

**Comment by saman-magnus** [comment]
x-ui.db Before the last update i use it
when i update to new version problems come , so after several time i see when i import x-ui.db crashes come .

**Comment by sudospaes** [comment]
I tested it and there was no problem. Can you upload the old database here for me to check more ?

**Comment by saman-magnus** [comment]
> Did you import it from the panel itself or manually ?

yes

**Comment by sudospaes** [comment]
> > Did you import it from the panel itself or manually ?
> 
> yes

Does this belong to another panel or is it the same panel? It seems that your database is corrupted.

**Comment by saman-magnus** [comment]
> > > Did you import it from the panel itself or manually ?
> > 
> > 
> > yes
> 
> Does this belong to another panel or is it the same panel? It seems that your database is corrupted.

This database was for the previous panel. But now the new panel is very good and professional. I am trying the new panel and it seems very attractive.
