### ISSUE TITLE
direct ir ip

### ISSUE THREAD

**Issue by ErfanTech** [sudospaes/x-ui#34]
i have enabled iran ip/domains to be connect directly but when load a iranian website it shows my server ip!

![Screenshot (791)](https://github.com/sudospaes/x-ui/assets/108360299/6b249427-0bbc-4011-8d88-0e7c4af9abf9)
![Screenshot (792)](https://github.com/sudospaes/x-ui/assets/108360299/9be73b46-ce67-4a45-a9b9-fda22da43710)

**Comment by misagh72** [comment]
direct ip is only work on ir server not foreign server 
u can only use block ir in foreign server

**Comment by ErfanTech** [comment]
thanks, i got it.
