### ISSUE TITLE
sync with alireza's latest x-ui release

### ISSUE THREAD

**Issue by ErfanTech** [sudospaes/x-ui#50]
can you please change the ui and use alireza's [new release](https://github.com/alireza0/x-ui/releases/tag/1.6.0)

**Comment by sudospaes** [comment]
I think Alireza's user interface design is not very good. And it is not compatible with the antd design language. What I think can be useful is to separate the xray settings from the panel settings

**Comment by ErfanTech** [comment]
Thanks. You are right but it is better than the current design at least.
By the way, what is your next step for developing the panel and your roadmap?

**Comment by sudospaes** [comment]
If rprx add xtls-switch property to xray. The panel is also update to it changes. It seems that the required options are already exist. And it just needs a little improvement. 

The appearance of the panel does not affect its performance. Also, I remember that the appearance changes applied to Alireza's panel cause its user interface to be slow. It seems to be more optimal to use the look provided by antd. It also maintains its simplicity and beauty

**Comment by ErfanTech** [comment]
What do you mean by `xtls-switch` ?

**Comment by sudospaes** [comment]
> What do you mean by `xtls-switch` ?

Its a flow like xtls-rprx-vision

**Comment by sudospaes** [comment]
Regarding your issue, the mobile mode has now been added in [v0.4.8.0](https://github.com/sudospaes/x-ui/releases/tag/v0.4.8.0)

**Comment by ErfanTech** [comment]
> Regarding your issue, the mobile mode has now been added in [v0.4.8.0](https://github.com/sudospaes/x-ui/releases/tag/v0.4.8.0)

Thank you for the update! 
I tried it out and like it.
